import React from 'react'
import {
  AccountingChip, AIChip, ConceptionChip, DockerChip, FlutterChip, GoogleAdminChip, GoogleCloudChip,
  InfraChip, Love2DChip, LuaChip, MetabaseChip, MuiChip, N8nChip, NextjsChip, NodejsChip, NumpyChip, PlanningChip,
  PythonChip, PyTorchChip, ReactChip, ReactNativeChip, SafetyChip, StaffChip, SupabaseChip, TailwindChip
} from './TechChip'

export type ProjectPreview = {
  src: string
  width: number
  height: number
  poster?: string
}

export type ProjectProps = {
  title: string
  id: string
  subtitle?: string
  lilTags?: Record<string, string>
  techTags?: React.ReactNode[]
  link?: string
  preview?: ProjectPreview
  description: React.ReactNode
  color: string
  status: string
  instaUrl?: string
  tiktokUrl?: string
  since?: string
  categories?: string[]
}

export const projectsEn: ProjectProps[] = [
  {
    subtitle: 'Setup, teardown & safety at',
    title: 'Orion Festival',
    id: 'orion-festival',
    lilTags: { 'Edition': 'First', 'Duration': '2 days', 'Festival-goers': '5,000' },
    techTags: [<StaffChip key="s" />, <PlanningChip key="p" />, <SafetyChip key="safety" />],
    link: 'https://orionfestival.ch/',
    preview: { src: 'videos/orion.mp4', width: 720, height: 1280, poster: 'videos/posters/orion.webp' },
    color: '#015f9c',
    description: <p>First edition of <a href="https://orionfestival.ch/" target="_blank" rel="noreferrer">Orion Festival</a> in Bernex: two days and 5,000 festival-goers over the weekend, far more than expected. A hugely successful launch: the beer stocked for both evenings sold out by 9 p.m. on the first night. Coordinated the setup and teardown of the stages, carried out by <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a>, and was responsible for safety throughout the event.</p>,
    status: 'Just getting started',
    instaUrl: 'https://www.instagram.com/orionfestival.ch/',
    tiktokUrl: 'https://www.tiktok.com/@orionfestival.ch',
    categories: ['assoc'],
  },
  {
    subtitle: 'Co-founder & CTO',
    title: 'Meky',
    id: 'meky',
    lilTags: { 'Team': 'of 3' },
    techTags: [<NextjsChip key="nj" />, <SupabaseChip key="sb" />, <DockerChip key="d" />, <InfraChip key="i" />, <AIChip key="ai" />],
    link: 'https://meky.ch/',
    preview: { src: 'images/meky/screenshot.webp', width: 787, height: 1398 },
    color: '#22CC93',
    description: <p>SaaS platform offering digital QR code menus with 3D dish visualization for restaurants. Built by orchestrating AI coding agents in constrained environments. Self-hosted infrastructure. Clients acquired via direct outreach in French-speaking Switzerland. Registered in the Swiss commercial registry.</p>,
    status: 'Completed and discontinued',
    categories: ['dev'],
  },
  {
    subtitle: 'Operations Optimization & AI at',
    title: 'Physio 7',
    id: 'physio7',
    lilTags: { 'Centers': '8', 'Employees': '60+', 'Internship': '4 months' },
    techTags: [<AIChip key="ai" />, <MetabaseChip key="mb" />, <InfraChip key="i" />, <N8nChip key="n8n" />],
    link: 'https://physio-7.ch/',
    preview: { src: 'videos/physio7.mp4', width: 682, height: 1280, poster: 'videos/posters/physio7.webp' },
    color: '#F29100',
    description: <p>Sole technical profile in a network of 8 physiotherapy centers. Responsible for process automation, business intelligence, AI integration, internal software development, and server infrastructure management. Enabling data-driven decisions at board level through self-hosted analytics tools and AI agents. Continuing to work there freely after the end of the full-time internship.</p>,
    status: 'Working there',
    instaUrl: 'https://www.instagram.com/physiosept/',
    since: 'August 2025',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Freelance development',
    title: 'Thaqi Renovation',
    id: 'thaqi',
    lilTags: { 'Developed in': '4 hours' },
    techTags: [<NextjsChip key="nj" />, <TailwindChip key="t" />, <AIChip key="ai" />],
    link: 'https://thaqirenovation.ch/',
    preview: { src: 'videos/thaqi.mp4', width: 614, height: 1280, poster: 'videos/posters/thaqi.webp' },
    color: '#0078b6',
    description: <p>Full website design and development for a Swiss renovation company. Built from scratch including responsive design, SEO optimization, and deployment. First time discovering and leveraging AI coding agents, significantly accelerating the development process.</p>,
    status: 'Delivered',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Freelance infrastructure',
    title: 'Koriox',
    id: 'koriox',
    techTags: [<DockerChip key="d" />, <InfraChip key="i" />],
    link: 'https://koriox.ch/',
    preview: { src: 'images/koriox/screenshot.webp', width: 769, height: 1367 },
    color: '#1e3a5f',
    description: <p>Infrastructure management and production deployment for a client-built application (Lovable). Handled the full mise en production including server setup, Docker containerization, domain configuration, and deployment pipeline. Ongoing maintenance and monitoring.</p>,
    status: 'Delivered',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'BSc in',
    title: 'Communication Systems',
    id: 'bsc-sc',
    lilTags: { 'University': 'EPFL', 'Duration': '3 years', 'GPA': '5.19/6' },
    link: 'https://www.epfl.ch/schools/ic/education/bachelor-in-communication-systems/',
    preview: { src: 'images/bsc-sc/diploma.webp', width: 1300, height: 2060 },
    color: '#e10000',
    description: <p>Bachelor&apos;s degree in Communication Systems at EPFL, covering a broad foundation in computer science, telecommunications, and information security.</p>,
    status: 'Completed',
    categories: ['academic'],
  },
  {
    subtitle: 'Bachelor thesis at EPFL DLAB',
    title: 'LLMojis',
    id: 'llmojis',
    lilTags: { 'Lab': 'DLAB', 'Supervisor': 'Robert West', 'Grade': '6' },
    techTags: [<ReactChip key="r" />, <AIChip key="ai" />],
    link: 'https://emojinize.xyz/',
    preview: { src: 'videos/llmojis.mp4', width: 688, height: 1280, poster: 'videos/posters/llmojis.webp' },
    color: '#facc15',
    description: <p>Research project at <a href="https://dlab.epfl.ch/" target="_blank" rel="noreferrer">EPFL DLAB</a> analyzing how LLMs behave in constrained environments, specifically emoji-only communication, compared to human players. Built an online multiplayer game where players communicate words using only emojis, and an LLM arena benchmarking various models under the same conditions. Research publication forthcoming.</p>,
    status: 'Completed',
    since: '2025',
    categories: ['academic', 'dev'],
  },
  {
    subtitle: 'Lead developer',
    title: 'Iglow',
    id: 'iglow',
    lilTags: { 'Team': 'of 7' },
    techTags: [<FlutterChip key="f" />, <ReactChip key="r" />, <ConceptionChip key="c" />],
    preview: { src: 'videos/iglow.mp4', width: 720, height: 1280, poster: 'videos/posters/iglow.webp' },
    color: '#dc0028',
    description: <p>Smart jacket improving cyclist visibility at night with light patterns signaling intentions. Built the website and the companion app for customizing patterns.</p>,
    status: 'Released soon',
    categories: ['dev'],
    link: 'https://iglow.swiss/',
  },
  {
    subtitle: 'Development of',
    title: 'Super S8000',
    id: 'ss8000',
    lilTags: { 'Work time': '8 weeks', 'Budget': 'CHF270', 'Engines': '6', 'Team': 'of 6' },
    techTags: [<ConceptionChip key="c" />, <PythonChip key="p" />, <PyTorchChip key="pt" />, <NumpyChip key="n" />],
    preview: { src: 'videos/ss8.mp4', width: 200, height: 338, poster: 'videos/posters/ss8.webp' },
    color: '#01a63e',
    description: <p>The <a href="https://github.com/epfl-cs358/2024fa-superscanner8000" target="_blank" rel="noreferrer">SuperScanner8000</a> is a robot that scans a selected object in 3D. It moves to take photos from different angles, which it uses in <a href="https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/" target="_blank" rel="noreferrer">3DGS</a> for 3D model reconstruction. Object detection is done via <a href="https://github.com/Gy920/segment-anything-2-real-time" target="_blank" rel="noreferrer">a variant of Segment Anything 2</a>.</p>,
    status: 'Completed',
    since: 'December 2024',
    categories: ['academic', 'dev'],
  },
  {
    title: 'La NDLM 24',
    id: 'ndlm24',
    subtitle: 'Operations Manager',
    lilTags: { 'Date': '05.10.24', 'Participants': '2400', 'Staffs': '180', 'Bars': '4', 'Stages': '2' },
    techTags: [<StaffChip key="s" />, <PlanningChip key="p" />],
    preview: { src: 'videos/ndlm24.mp4', width: 320, height: 568, poster: 'videos/posters/ndlm24.webp' },
    color: '#c3a36a',
    description: <p>Official <a href="https://www.epfl.ch/" target="_blank" rel="noreferrer">EPFL</a> master&apos;s graduation event at the <a href="https://www.stcc.ch/" target="_blank" rel="noreferrer">SwissTech Convention Center</a>. Coordinated site setup/teardown and managed 180 volunteers.</p>,
    status: 'Former committee Member',
    instaUrl: 'https://www.instagram.com/ndlm_epfl/',
    categories: ['assoc'],
  },
  {
    title: 'Lümm x 2221',
    id: 'lummx2221',
    subtitle: 'DJ sets & LED panels',
    lilTags: { 'Date': '28.09.24', 'DJs': '6', 'Participants': '500', 'Staffs': '20', 'Beer': 'CHF3' },
    techTags: [<StaffChip key="s" />, <AccountingChip key="a" />],
    preview: { src: 'videos/lummx2221.mp4', width: 324, height: 576, poster: 'videos/posters/lummx2221.webp' },
    color: 'silver',
    description: <p>Fourth <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a> edition with <a href="https://2221.ch/" target="_blank" rel="noreferrer">2221.ch</a>. Debuted LED panels with VJing by <a href="https://www.instagram.com/stories/b0nk_13" target="_blank" rel="noreferrer">b0nk</a>. Supported by <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> and <a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Big banger',
    instaUrl: 'https://www.instagram.com/lumm.love/',
    categories: ['assoc'],
  },
  {
    title: 'Artiphys',
    id: 'artiphys-website',
    subtitle: 'Webmaster at',
    lilTags: { 'Events': '4', 'Festival-goers': '1200', 'Committee members': '29' },
    techTags: [<ReactChip key="r" />, <TailwindChip key="t" />, <GoogleAdminChip key="g" />],
    link: 'https://artiphys.ch/',
    preview: { src: 'videos/artiphys.mp4', width: 320, height: 568, poster: 'videos/posters/artiphys.webp' },
    color: '#f9a5ee',
    description: <p>Webmaster for the 2025 edition of <a href="https://www.artiphys.ch/" target="_blank" rel="noreferrer">Artiphys</a>. Redesigned the website and managed entries/ticketing for each event.</p>,
    status: 'Committee Member',
    instaUrl: 'https://www.instagram.com/artiphysfestival/',
    since: 'June 2024',
    categories: ['assoc', 'dev'],
  },
  {
    title: 'Okalo.ch',
    id: 'okalo',
    subtitle: 'Online book exchange',
    lilTags: { 'Users': '700+', 'Books listed/sold': '6,000+' },
    techTags: [<ConceptionChip key="c" />, <ReactChip key="r" />, <NodejsChip key="n" />, <MuiChip key="m" />],
    link: 'https://www.okalo.ch/',
    preview: { src: 'videos/okalo.mp4', width: 320, height: 568, poster: 'videos/posters/okalo.webp' },
    color: '#0496FF',
    description: <p>Platform used in a dozen+ Geneva colleges for buying and selling second-hand textbooks between students.</p>,
    status: 'Active',
    instaUrl: 'https://www.instagram.com/okalo.ch/',
    since: '2022',
    categories: ['dev'],
  },
  {
    title: 'LÜMM C',
    id: 'lummc',
    subtitle: 'Parade, concerts & DJ sets',
    lilTags: { 'Date': '11.05.24', 'Participants': '700', 'Staffs': '46', 'Beer': 'CHF2' },
    link: 'https://www.lumm.love/',
    preview: { src: 'videos/lummc.mp4', width: 320, height: 568, poster: 'videos/posters/lummc.webp' },
    color: 'rgb(205, 24, 27)',
    techTags: [<StaffChip key="s" />, <PlanningChip key="p" />, <AccountingChip key="a" />],
    description: <p>Third <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a> edition, co-founded in early 2024. With <a href="https://satellite.bar/" target="_blank" rel="noreferrer">Satellite</a> bar and <a href="https://artepoly.agepoly.ch/" target="_blank" rel="noreferrer">ArtePoly</a>. Supported by <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> and <a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Big success',
    instaUrl: 'https://www.instagram.com/lumm.love/',
    categories: ['assoc'],
  },
  {
    title: 'Morii',
    id: 'morii',
    subtitle: 'Shared photodump',
    lilTags: { 'Tested at': 'lümm c', 'Photos shared': '200' },
    link: 'https://morii.lumm.love/',
    preview: { src: 'videos/morii.mp4', width: 320, height: 568, poster: 'videos/posters/morii.webp' },
    color: 'white',
    techTags: [<ConceptionChip key="c" />, <GoogleCloudChip key="gc" />, <ReactChip key="r" />, <NodejsChip key="n" />],
    description: <p>Photo-sharing platform to replace the classic <span style={{ fontStyle: 'italic' }}>&quot;Send your photos to the group.&quot;</span> Sorted photos, no quality loss.</p>,
    status: 'On hold',
    since: 'May 2024',
    categories: ['dev'],
  },
  {
    title: 'Dasher',
    id: 'dasher',
    subtitle: 'Mobile game',
    lilTags: { 'Platform': 'Android', 'Downloads': '60' },
    preview: { src: 'videos/dasher.mp4', width: 320, height: 568, poster: 'videos/posters/dasher.webp' },
    color: '#d0b0e7',
    techTags: [<LuaChip key="l" />, <Love2DChip key="lv" />],
    description: <p>Mobile game built during covid. <a href="https://lionstudios.cc/" target="_blank" rel="noreferrer">LionStudios</a> showed interest in publishing, but player feedback wasn&apos;t strong enough to proceed.</p>,
    status: 'Failure',
    since: '2020',
    categories: ['dev'],
  },
  {
    title: 'Parkeur',
    id: 'parkeur',
    subtitle: 'Mobile app',
    lilTags: { 'Platform': 'Android', 'Released on': 'Google Play' },
    preview: { src: 'videos/parkeur.mp4', width: 320, height: 650, poster: 'videos/posters/parkeur.webp' },
    color: '#4c63ec',
    techTags: [<ConceptionChip key="c" />, <ReactNativeChip key="rn" />],
    description: <p>Language vocabulary learning app with adaptive modes and vocabulary list scanning.</p>,
    status: 'Finished',
    since: '2019',
    categories: ['dev'],
  },
]

type ProjectTranslation = Pick<ProjectProps, 'title' | 'description' | 'status'> &
  Partial<Pick<ProjectProps, 'subtitle' | 'lilTags' | 'since'>>

const projectTranslationsFr: ProjectTranslation[] = [
  {
    subtitle: 'Montage, démontage et sécurité pour',
    title: 'Orion Festival',
    lilTags: { 'Édition': 'Première', 'Durée': '2 jours', 'Festivaliers': '5 000' },
    description: <p>Première édition de l&apos;<a href="https://orionfestival.ch/" target="_blank" rel="noreferrer">Orion Festival</a> à Bernex : deux jours et 5 000 festivaliers sur le week-end, bien plus que prévu. Un lancement couronné de succès : le stock de bière prévu pour les deux soirées était épuisé à 21 h dès la première nuit. Coordination du montage et du démontage des scènes, assurés par <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a>, et responsabilité de la sécurité pendant tout l&apos;événement.</p>,
    status: 'L’aventure ne fait que commencer',
  },
  {
    subtitle: 'Cofondateur et CTO',
    title: 'Meky',
    lilTags: { 'Équipe': 'de 3 personnes' },
    description: <p>Plateforme SaaS proposant aux restaurants des menus numériques par code QR avec visualisation 3D des plats. Développée en orchestrant des agents de programmation par IA dans des environnements contraints. Infrastructure auto-hébergée. Clients acquis par démarchage direct en Suisse romande. Entreprise inscrite au registre du commerce suisse.</p>,
    status: 'Terminé et abandonné',
  },
  {
    subtitle: 'Optimisation des opérations et IA chez',
    title: 'Physio 7',
    lilTags: { 'Centres': '8', 'Employés': '60+', 'Stage': '4 mois' },
    description: <p>Seul profil technique au sein d&apos;un réseau de huit centres de physiothérapie. Responsable de l&apos;automatisation des processus, de l&apos;informatique décisionnelle, de l&apos;intégration de l&apos;IA, du développement de logiciels internes et de la gestion de l&apos;infrastructure serveur. Mise à disposition d&apos;outils d&apos;analyse auto-hébergés et d&apos;agents IA permettant au conseil d&apos;administration de prendre des décisions fondées sur les données. Poursuite libre de cette activité après la fin du stage à temps plein.</p>,
    status: 'En poste',
    since: 'Août 2025',
  },
  {
    subtitle: 'Développement en freelance',
    title: 'Thaqi Renovation',
    lilTags: { 'Développé en': '4 heures' },
    description: <p>Conception et développement complets du site d&apos;une entreprise suisse de rénovation. Réalisé de A à Z, avec une interface adaptative, l&apos;optimisation du référencement et la mise en production. Première découverte et utilisation d&apos;agents de programmation par IA, qui ont considérablement accéléré le développement.</p>,
    status: 'Livré',
  },
  {
    subtitle: 'Infrastructure en freelance',
    title: 'Koriox',
    description: <p>Gestion de l&apos;infrastructure et déploiement en production d&apos;une application créée par un client avec Lovable. Prise en charge complète de la mise en production : configuration du serveur, conteneurisation avec Docker, configuration du domaine et chaîne de déploiement. Maintenance et supervision continues.</p>,
    status: 'Livré',
  },
  {
    subtitle: 'Bachelor en',
    title: 'Systèmes de communication',
    lilTags: { 'Université': 'EPFL', 'Durée': '3 ans', 'Moyenne': '5,19/6' },
    description: <p>Bachelor en systèmes de communication à l&apos;EPFL, offrant de solides bases en informatique, en télécommunications et en sécurité de l&apos;information.</p>,
    status: 'Terminé',
  },
  {
    subtitle: 'Projet de bachelor à l’EPFL DLAB',
    title: 'LLMojis',
    lilTags: { 'Laboratoire': 'DLAB', 'Superviseur': 'Robert West', 'Note': '6' },
    description: <p>Projet de recherche à l&apos;<a href="https://dlab.epfl.ch/" target="_blank" rel="noreferrer">EPFL DLAB</a> analysant le comportement des LLM dans des environnements contraints, en particulier lors de communications exclusivement composées d&apos;émojis, et le comparant à celui de joueurs humains. Développement d&apos;un jeu multijoueur en ligne dans lequel les joueurs communiquent des mots uniquement à l&apos;aide d&apos;émojis, ainsi que d&apos;une arène de LLM évaluant différents modèles dans les mêmes conditions. Publication scientifique à paraître.</p>,
    status: 'Terminé',
    since: '2025',
  },
  {
    subtitle: 'Développeur principal',
    title: 'Iglow',
    lilTags: { 'Équipe': 'de 7 personnes' },
    description: <p>Veste intelligente améliorant la visibilité nocturne des cyclistes grâce à des motifs lumineux signalant leurs intentions. Développement du site web et de l&apos;application associée permettant de personnaliser les motifs.</p>,
    status: 'Sortie prochaine',
  },
  {
    subtitle: 'Développement de',
    title: 'Super S8000',
    lilTags: { 'Temps de travail': '8 semaines', 'Budget': '270 CHF', 'Moteurs': '6', 'Équipe': 'de 6 personnes' },
    description: <p>Le <a href="https://github.com/epfl-cs358/2024fa-superscanner8000" target="_blank" rel="noreferrer">SuperScanner8000</a> est un robot qui numérise en 3D un objet sélectionné. Il se déplace pour prendre des photos sous différents angles, puis les utilise avec <a href="https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/" target="_blank" rel="noreferrer">3DGS</a> afin de reconstruire un modèle 3D. La détection de l&apos;objet repose sur <a href="https://github.com/Gy920/segment-anything-2-real-time" target="_blank" rel="noreferrer">une variante de Segment Anything 2</a>.</p>,
    status: 'Terminé',
    since: 'Décembre 2024',
  },
  {
    title: 'La NDLM 24',
    subtitle: 'Responsable des opérations',
    lilTags: { 'Date': '05.10.24', 'Participants': '2 400', 'Bénévoles': '180', 'Bars': '4', 'Scènes': '2' },
    description: <p>Événement officiel de remise des diplômes de master de l&apos;<a href="https://www.epfl.ch/" target="_blank" rel="noreferrer">EPFL</a> au <a href="https://www.stcc.ch/" target="_blank" rel="noreferrer">SwissTech Convention Center</a>. Coordination du montage et du démontage du site, ainsi que gestion de 180 bénévoles.</p>,
    status: 'Ancien membre du comité',
  },
  {
    title: 'Lümm x 2221',
    subtitle: 'DJ sets et panneaux LED',
    lilTags: { 'Date': '28.09.24', 'DJ': '6', 'Participants': '500', 'Bénévoles': '20', 'Bière': '3 CHF' },
    description: <p>Quatrième édition de <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a>, organisée avec <a href="https://2221.ch/" target="_blank" rel="noreferrer">2221.ch</a>. Première utilisation de panneaux LED accompagnés du VJing de <a href="https://www.instagram.com/stories/b0nk_13" target="_blank" rel="noreferrer">b0nk</a>. Avec le soutien de <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> et d&apos;<a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Énorme soirée',
  },
  {
    title: 'Artiphys',
    subtitle: 'Webmaster chez',
    lilTags: { 'Événements': '4', 'Festivaliers': '1 200', 'Membres du comité': '29' },
    description: <p>Webmaster de l&apos;édition 2025 d&apos;<a href="https://www.artiphys.ch/" target="_blank" rel="noreferrer">Artiphys</a>. Refonte du site web et gestion des inscriptions et de la billetterie de chaque événement.</p>,
    status: 'Membre du comité',
    since: 'Juin 2024',
  },
  {
    title: 'Okalo.ch',
    subtitle: 'Bourse aux livres en ligne',
    lilTags: { 'Utilisateurs': '700+', 'Livres proposés/vendus': '6 000+' },
    description: <p>Plateforme utilisée dans plus d&apos;une douzaine de collèges genevois pour l&apos;achat et la vente de manuels scolaires d&apos;occasion entre élèves.</p>,
    status: 'Actif',
    since: '2022',
  },
  {
    title: 'LÜMM C',
    subtitle: 'Parade, concerts et DJ sets',
    lilTags: { 'Date': '11.05.24', 'Participants': '700', 'Bénévoles': '46', 'Bière': '2 CHF' },
    description: <p>Troisième édition de <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a>, cofondée début 2024. Avec le bar <a href="https://satellite.bar/" target="_blank" rel="noreferrer">Satellite</a> et <a href="https://artepoly.agepoly.ch/" target="_blank" rel="noreferrer">ArtePoly</a>. Avec le soutien de <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> et d&apos;<a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Grand succès',
  },
  {
    title: 'Morii',
    subtitle: 'Album photo partagé',
    lilTags: { 'Testé à': 'LÜMM C', 'Photos partagées': '200' },
    description: <p>Plateforme de partage de photos conçue pour remplacer le classique <span style={{ fontStyle: 'italic' }}>&quot;Envoyez vos photos dans le groupe.&quot;</span> Photos triées, sans perte de qualité.</p>,
    status: 'En pause',
    since: 'Mai 2024',
  },
  {
    title: 'Dasher',
    subtitle: 'Jeu mobile',
    lilTags: { 'Plateforme': 'Android', 'Téléchargements': '60' },
    description: <p>Jeu mobile développé pendant le Covid. <a href="https://lionstudios.cc/" target="_blank" rel="noreferrer">LionStudios</a> s&apos;est montré intéressé par sa publication, mais les retours des joueurs n&apos;étaient pas assez positifs pour poursuivre.</p>,
    status: 'Échec',
    since: '2020',
  },
  {
    title: 'Parkeur',
    subtitle: 'Application mobile',
    lilTags: { 'Plateforme': 'Android', 'Publié sur': 'Google Play' },
    description: <p>Application d&apos;apprentissage du vocabulaire avec des modes adaptatifs et la numérisation de listes de vocabulaire.</p>,
    status: 'Terminé',
    since: '2019',
  },
]

export const projectsFr: ProjectProps[] = projectsEn.map((project, index) => ({
  ...project,
  ...projectTranslationsFr[index],
}))
