import React from 'react'
import {
  AccountingChip, AIChip, ConceptionChip, DockerChip, FlutterChip, GoogleAdminChip, GoogleCloudChip,
  InfraChip, Love2DChip, LuaChip, MetabaseChip, MuiChip, N8nChip, NextjsChip, NodejsChip, NumpyChip, PlanningChip,
  PythonChip, PyTorchChip, ReactChip, ReactNativeChip, StaffChip, SupabaseChip, TailwindChip
} from './TechChip'

export type ProjectProps = {
  title: string
  id: string
  subtitle?: string
  lilTags?: Record<string, string>
  techTags?: React.ReactNode[]
  link?: string
  preview?: string[]
  description: React.ReactNode
  color: string
  status: string
  instaUrl?: string
  since?: string
  categories?: string[]
}

export const projectsEn: ProjectProps[] = [
  {
    subtitle: 'Co-founder & CTO',
    title: 'Meky',
    id: 'meky',
    lilTags: { 'Team': 'of 3' },
    techTags: [<NextjsChip key="nj" />, <SupabaseChip key="sb" />, <DockerChip key="d" />, <InfraChip key="i" />, <AIChip key="ai" />],
    link: 'https://meky.ch/',
    preview: ['images/meky/screenshot.png'],
    color: '#22CC93',
    description: <p>SaaS platform offering digital QR code menus with 3D dish visualization for restaurants. Built by orchestrating AI coding agents in constrained environments. Self-hosted infrastructure. Clients acquired via direct outreach in French-speaking Switzerland. Registered in the Swiss commercial registry.</p>,
    status: 'Working on it',
    since: 'January 2025',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Operations Optimization & AI at',
    title: 'Physio 7',
    id: 'physio7',
    lilTags: { 'Centers': '8', 'Employees': '60+', 'Internship': '4 months' },
    techTags: [<AIChip key="ai" />, <MetabaseChip key="mb" />, <InfraChip key="i" />, <N8nChip key="n8n" />],
    link: 'https://physio-7.ch/',
    preview: ['videos/physio7.mp4'],
    color: '#F29100',
    description: <p>Sole technical profile in a network of 8 physiotherapy centers. Responsible for process automation, business intelligence, AI integration, internal software development, and server infrastructure management. Enabling data-driven decisions at board level through self-hosted analytics tools and AI agents. Continuing to work there freely after the end of the full-time internship.</p>,
    status: 'Working there',
    instaUrl: 'https://www.instagram.com/physiosept/',
    since: 'August 2025',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Freelance development',
    title: 'Thaqi Renovation',
    id: 'thaqi',
    lilTags: { 'Developed in': '4 hours' },
    techTags: [<NextjsChip key="nj" />, <TailwindChip key="t" />, <AIChip key="ai" />],
    link: 'https://thaqirenovation.ch/',
    preview: ['videos/thaqi.mp4'],
    color: '#0078b6',
    description: <p>Full website design and development for a Swiss renovation company. Built from scratch including responsive design, SEO optimization, and deployment. First time discovering and leveraging AI coding agents, significantly accelerating the development process.</p>,
    status: 'Delivered',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Freelance infrastructure',
    title: 'Koriox',
    id: 'koriox',
    techTags: [<DockerChip key="d" />, <InfraChip key="i" />],
    link: 'https://koriox.ch/',
    preview: ['images/koriox/screenshot.png'],
    color: '#1e3a5f',
    description: <p>Infrastructure management and production deployment for a client-built application (Lovable). Handled the full mise en production including server setup, Docker containerization, domain configuration, and deployment pipeline. Ongoing maintenance and monitoring.</p>,
    status: 'Delivered',
    categories: ['dev', 'pro'],
  },
  {
    subtitle: 'Lead developer',
    title: 'Iglow',
    id: 'iglow',
    lilTags: { 'Team': 'of 7' },
    techTags: [<FlutterChip key="f" />, <ReactChip key="r" />, <ConceptionChip key="c" />],
    preview: ['videos/iglow.mp4'],
    color: '#dc0028',
    description: <p>Smart jacket improving cyclist visibility at night with light patterns signaling intentions. Built the website and the companion app for customizing patterns.</p>,
    status: 'Released soon',
    categories: ['dev'],
    link: 'https://iglow.swiss/',
  },
  {
    subtitle: 'Development of',
    title: 'Super S8000',
    id: 'ss8000',
    lilTags: { 'Work time': '8 weeks', 'Budget': 'CHF270', 'Engines': '6', 'Team': 'of 6' },
    techTags: [<ConceptionChip key="c" />, <PythonChip key="p" />, <PyTorchChip key="pt" />, <NumpyChip key="n" />],
    preview: ['videos/ss8.mp4'],
    color: '#01a63e',
    description: <p>The <a href="https://github.com/epfl-cs358/2024fa-superscanner8000" target="_blank" rel="noreferrer">SuperScanner8000</a> is a robot that scans a selected object in 3D. It moves to take photos from different angles, which it uses in <a href="https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/" target="_blank" rel="noreferrer">3DGS</a> for 3D model reconstruction. Object detection is done via <a href="https://github.com/Gy920/segment-anything-2-real-time" target="_blank" rel="noreferrer">a variant of Segment Anything 2</a>.</p>,
    status: 'Completed',
    since: 'December 2024',
    categories: ['academic', 'dev'],
  },
  {
    title: 'La NDLM 24',
    id: 'ndlm24',
    subtitle: 'Operations Manager',
    lilTags: { 'Date': '05.10.24', 'Participants': '2400', 'Staffs': '180', 'Bars': '4', 'Stages': '2' },
    techTags: [<StaffChip key="s" />, <PlanningChip key="p" />],
    preview: ['videos/ndlm24.mp4'],
    color: '#c3a36a',
    description: <p>Official <a href="https://www.epfl.ch/" target="_blank" rel="noreferrer">EPFL</a> master&apos;s graduation event at the <a href="https://www.stcc.ch/" target="_blank" rel="noreferrer">SwissTech Convention Center</a>. Coordinated site setup/teardown and managed 180 volunteers.</p>,
    status: 'Former committee Member',
    instaUrl: 'https://www.instagram.com/ndlm_epfl/',
    categories: ['assoc'],
  },
  {
    title: 'Lümm x 2221',
    id: 'lummx2221',
    subtitle: 'DJ sets & LED panels',
    lilTags: { 'Date': '28.09.24', 'DJs': '6', 'Participants': '500', 'Staffs': '20', 'Beer': 'CHF3' },
    techTags: [<StaffChip key="s" />, <AccountingChip key="a" />],
    preview: ['videos/lummx2221.mp4'],
    color: 'silver',
    description: <p>Fourth <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a> edition with <a href="https://2221.ch/" target="_blank" rel="noreferrer">2221.ch</a>. Debuted LED panels with VJing by <a href="https://www.instagram.com/stories/b0nk_13" target="_blank" rel="noreferrer">b0nk</a>. Supported by <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> and <a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Big banger',
    instaUrl: 'https://www.instagram.com/lumm.love/',
    categories: ['assoc'],
  },
  {
    title: 'Artiphys',
    id: 'artiphys-website',
    subtitle: 'Webmaster at',
    lilTags: { 'Events': '4', 'Festival-goers': '1200', 'Committee members': '29' },
    techTags: [<ReactChip key="r" />, <TailwindChip key="t" />, <GoogleAdminChip key="g" />],
    link: 'https://artiphys.ch/',
    preview: ['videos/artiphys.mp4'],
    color: '#f9a5ee',
    description: <p>Webmaster for the 2025 edition of <a href="https://www.artiphys.ch/" target="_blank" rel="noreferrer">Artiphys</a>. Redesigned the website and managed entries/ticketing for each event.</p>,
    status: 'Committee Member',
    instaUrl: 'https://www.instagram.com/artiphysfestival/',
    since: 'June 2024',
    categories: ['assoc', 'dev'],
  },
  {
    title: 'Okalo.ch',
    id: 'okalo',
    subtitle: 'Online book exchange',
    lilTags: { 'Users': '700+', 'Books listed/sold': '6,000+' },
    techTags: [<ConceptionChip key="c" />, <ReactChip key="r" />, <NodejsChip key="n" />, <MuiChip key="m" />],
    link: 'https://www.okalo.ch/',
    preview: ['videos/okalo.mp4'],
    color: '#0496FF',
    description: <p>Platform used in a dozen+ Geneva colleges for buying and selling second-hand textbooks between students.</p>,
    status: 'Active',
    instaUrl: 'https://www.instagram.com/okalo.ch/',
    since: '2022',
    categories: ['dev'],
  },
  {
    title: 'LÜMM C',
    id: 'lummc',
    subtitle: 'Parade, concerts & DJ sets',
    lilTags: { 'Date': '11.05.24', 'Participants': '700', 'Staffs': '46', 'Beer': 'CHF2' },
    link: 'https://www.lumm.love/',
    preview: ['videos/lummc.mp4'],
    color: 'rgb(205, 24, 27)',
    techTags: [<StaffChip key="s" />, <PlanningChip key="p" />, <AccountingChip key="a" />],
    description: <p>Third <a href="https://www.lumm.love/" target="_blank" rel="noreferrer">LÜMM</a> edition, co-founded in early 2024. With <a href="https://satellite.bar/" target="_blank" rel="noreferrer">Satellite</a> bar and <a href="https://artepoly.agepoly.ch/" target="_blank" rel="noreferrer">ArtePoly</a>. Supported by <a href="https://lanebuleuse.ch/" target="_blank" rel="noreferrer">La Nébuleuse</a> and <a href="https://www.eltonymate.com/" target="_blank" rel="noreferrer">El Tony Mate</a>.</p>,
    status: 'Big success',
    instaUrl: 'https://www.instagram.com/lumm.love/',
    categories: ['assoc'],
  },
  {
    title: 'Morii',
    id: 'morii',
    subtitle: 'Shared photodump',
    lilTags: { 'Tested at': 'lümm c', 'Photos shared': '200' },
    link: 'https://morii.lumm.love/',
    preview: ['videos/morii.mp4'],
    color: 'white',
    techTags: [<ConceptionChip key="c" />, <GoogleCloudChip key="gc" />, <ReactChip key="r" />, <NodejsChip key="n" />],
    description: <p>Photo-sharing platform to replace the classic <span style={{ fontStyle: 'italic' }}>&quot;Send your photos to the group.&quot;</span> Sorted photos, no quality loss.</p>,
    status: 'On hold',
    since: 'May 2024',
    categories: ['dev'],
  },
  {
    title: 'Dasher',
    id: 'dasher',
    subtitle: 'Mobile game',
    lilTags: { 'Platform': 'Android', 'Downloads': '60' },
    preview: ['videos/dasher.mp4'],
    color: '#d0b0e7',
    techTags: [<LuaChip key="l" />, <Love2DChip key="lv" />],
    description: <p>Mobile game built during covid. <a href="https://lionstudios.cc/" target="_blank" rel="noreferrer">LionStudios</a> showed interest in publishing, but player feedback wasn&apos;t strong enough to proceed.</p>,
    status: 'Failure',
    since: '2020',
    categories: ['dev'],
  },
  {
    title: 'Parkeur',
    id: 'parkeur',
    subtitle: 'Mobile app',
    lilTags: { 'Platform': 'Android', 'Released on': 'Google Play' },
    preview: ['videos/parkeur.mp4'],
    color: '#4c63ec',
    techTags: [<ConceptionChip key="c" />, <ReactNativeChip key="rn" />],
    description: <p>Language vocabulary learning app with adaptive modes and vocabulary list scanning.</p>,
    status: 'Finished',
    since: '2019',
    categories: ['dev'],
  },
]
